# Generated by Django 5.2.15 on 2026-07-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.salon'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.salon'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.supplier'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['salon', '-created_at'], name='inventory_s_salon_i_9a6471_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['salon', 'active'], name='inventory_p_salon_i_2ea370_idx'),
        ),
    ]
