# Generated by Django 5.2.15 on 2026-07-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='color',
            field=models.CharField(default='#E0E7FF', max_length=7),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.operator'),
        ),
    ]
