# Generated by Django 5.2.15 on 2026-07-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confermato'), ('checked_in', 'Check-in'), ('in_progress', 'In corso'), ('closed', 'Chiuso'), ('no_show', 'No-show'), ('cancelled', 'Annullato')], default='confirmed', max_length=20)),
                ('deposit_status', models.CharField(choices=[('none', 'Nessuno'), ('required', 'Richiesto'), ('paid', 'Pagato'), ('refunded', 'Rimborsato'), ('forfeited', 'Trattenuto')], default='none', max_length=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('flexible', models.BooleanField(default=False)),
                ('created_via', models.CharField(choices=[('dashboard', 'Dashboard'), ('app', 'App cliente')], default='dashboard', max_length=10)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_late', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_min', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('duration_min', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('morning', 'Mattina'), ('afternoon', 'Pomeriggio'), ('weekend', 'Weekend'), ('any', 'Qualsiasi'), ('exact', 'Giorni/orario precisi')], default='any', max_length=10)),
                ('exact_days', models.JSONField(blank=True, default=list)),
                ('exact_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Attiva'), ('contacted', 'Contattata'), ('booked', 'Prenotata'), ('expired', 'Scaduta')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Waitlist entries',
                'ordering': ['created_at'],
            },
        ),
    ]
