# Generated by Django 5.2.15 on 2026-07-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clients.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.location'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='staff.operator'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.salon'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agenda.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_items', to='staff.operator'),
        ),
        migrations.AddField(
            model_name='appointmentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_items', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='pause',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='staff.operator'),
        ),
        migrations.AddField(
            model_name='pause',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='core.salon'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='clients.client'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='staff.operator'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.salon'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='catalog.service'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['salon', 'start'], name='agenda_appo_salon_i_34771f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['operator', 'start'], name='agenda_appo_operato_54b2d8_idx'),
        ),
    ]
