# Generated by Django 5.2.15 on 2026-07-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='soak_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
