# Generated by Django 5.2.16 on 2026-07-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_appointmentservice_soak_min'),
        ('clients', '0001_initial'),
        ('core', '0003_salonsettings_opening_hours'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='yourang_event_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_via',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('app', 'App cliente'), ('yourang', 'Yourang')], default='dashboard', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('yourang_event_id', ''), _negated=True), fields=('salon', 'yourang_event_id'), name='uniq_appointment_salon_yourang_event'),
        ),
    ]
