# Generated by Django 5.2.17 on 2026-09-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_appointment_yourang_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deposit_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='appointment',
            name='no_show_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='deposit_status',
            field=models.CharField(choices=[('none', 'Nessuno'), ('required', 'Richiesto'), ('paid', 'Pagato'), ('refund_due', 'Da rimborsare'), ('refunded', 'Rimborsato'), ('forfeited', 'Trattenuto')], default='none', max_length=10),
        ),
    ]
