# Generated by Django 5.2.17 on 2026-09-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_appointment_payment_intents_refund_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='auto_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_payment_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='forced',
            field=models.BooleanField(default=False),
        ),
    ]
