# Generated by Django 5.2.17 on 2026-09-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_appointment_deposit_hold_release_forced'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deposit_refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit_refunds',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='deposit_status',
            field=models.CharField(choices=[('none', 'Nessuno'), ('required', 'Richiesto'), ('paid', 'Pagato'), ('refund_due', 'Da rimborsare'), ('refunding', 'Rimborso in corso'), ('refunded', 'Rimborsato'), ('forfeited', 'Trattenuto')], default='none', max_length=10),
        ),
    ]
