# Generated by Django 5.2.17 on 2026-09-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_deposit_refunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deposit_checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
