# Generated by Django 5.2.17 on 2026-09-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_deposit_checkout_session'),
        ('clients', '0006_backfill_phone_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clients.client'),
        ),
    ]
