# Generated by Django 5.2.17 on 2026-09-22 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_protect_client_on_delete'),
        ('core', '0009_outboxevent_coalesce_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UndoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('create', 'Creazione'), ('move', 'Spostamento'), ('edit', 'Modifica'), ('split', 'Stacco'), ('cancel', 'Annullamento'), ('no_show', 'No-show'), ('status', 'Cambio stato'), ('pause_create', 'Pausa aggiunta'), ('pause_update', 'Pausa spostata'), ('pause_delete', 'Pausa rimossa')], max_length=20)),
                ('label', models.CharField(max_length=160)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undo_entries', to='core.salon')),
            ],
            options={
                'verbose_name_plural': 'Undo entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['salon', 'actor', '-created_at'], name='agenda_undo_salon_i_c1158d_idx')],
            },
        ),
    ]
