# Generated by Django 5.2.17 on 2026-09-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0010_undoentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="deposit_hold_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="deposit_link_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="deposit_stripe_account",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
