# Generated by Django 5.2.15 on 2026-07-03 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#A5B4FC', max_length=7)),
                ('role_title', models.CharField(blank=True, max_length=120)),
                ('hourly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cycle_weeks', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='core.location')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='core.salon')),
                ('services', models.ManyToManyField(blank=True, related_name='operators', to='catalog.service')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'operatrice',
                'verbose_name_plural': 'operatrici',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('type', models.CharField(choices=[('vacation', 'Ferie'), ('holiday', 'Permesso'), ('other', 'Altro')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='staff.operator')),
            ],
            options={
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_index', models.PositiveSmallIntegerField(default=0)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')])),
                ('start_min', models.PositiveSmallIntegerField()),
                ('end_min', models.PositiveSmallIntegerField()),
                ('break_start_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('break_end_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.operator')),
            ],
            options={
                'ordering': ['week_index', 'weekday', 'start_min'],
            },
        ),
    ]
