# Generated by Django 5.2.15 on 2026-07-03 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('default_lang', models.CharField(choices=[('it', 'It'), ('en', 'En')], default='it', max_length=2)),
                ('currency', models.CharField(default='EUR', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.salon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepositRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('amount_type', models.CharField(choices=[('pct', '%'), ('fixed', '€')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_rules', to='core.salon')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('brand_color', models.CharField(default='#6366F1', max_length=7)),
                ('agenda_fill', models.CharField(choices=[('free', 'Libero'), ('max_revenue', 'Massimo incasso')], default='free', max_length=20)),
                ('slot_recovery', models.CharField(choices=[('notify', 'Avvisa'), ('execute', 'Esegui')], default='notify', max_length=20)),
                ('lastminute_discount_cap', models.PositiveSmallIntegerField(default=0)),
                ('lastminute_monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flexible_enabled', models.BooleanField(default=True)),
                ('flexible_window_min', models.PositiveSmallIntegerField(default=30)),
                ('flexible_reward_pct', models.PositiveSmallIntegerField(default=10)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.salon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='core.salon')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_outbox_status_99ab3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=120)),
                ('type', models.CharField(max_length=60)),
                ('summary', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.location')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.salon')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['salon', '-created_at'], name='core_activi_salon_i_53ce8a_idx')],
            },
        ),
    ]
