# Generated by Django 5.2.15 on 2026-07-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonsettings',
            name='slot_interval_min',
            field=models.PositiveSmallIntegerField(choices=[(15, '15 minuti'), (20, '20 minuti'), (30, '30 minuti')], default=15),
        ),
    ]
