# Generated by Django 5.2.16 on 2026-07-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_salonsettings_slot_interval_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonsettings',
            name='opening_hours',
            field=models.TextField(blank=True, default=''),
        ),
    ]
