# Generated by Django 5.2.16 on 2026-07-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_salonsettings_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonsettings',
            name='deposit_deadline_action',
            field=models.CharField(choices=[('none', 'Solo avviso'), ('charge', 'Addebita la caparra sulla carta salvata'), ('cancel', "Annulla l'appuntamento e libera lo slot")], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='deposit_deadline_hours',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='deposit_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='late_cancel_charge_pct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='noshow_charge_delay_min',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='noshow_charge_mode',
            field=models.CharField(choices=[('manual', 'Manuale (decide lo staff)'), ('automatic', 'Automatico')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='noshow_charge_pct',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
