# Generated by Django 5.2.17 on 2026-09-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_salonsettings_privacy_policy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonsettings',
            name='opening_hours_week',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
