# Generated by Django 5.2.17 on 2026-09-16 19:42

from django.db import migrations, models


def optimized_fill_everywhere(apps, schema_editor):
    """La disponibilità intelligente (niente buchi invendibili) diventa il comportamento
    di tutti i saloni: il titolare può tornare a 'free' dalle Impostazioni."""
    SalonSettings = apps.get_model("core", "SalonSettings")
    SalonSettings.objects.filter(agenda_fill="free").update(agenda_fill="max_revenue")



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_salonsettings_opening_hours_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonsettings',
            name='cancel_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='deposit_hold_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='deposit_reminder_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='no_show_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='stripe_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='agenda_fill',
            field=models.CharField(choices=[('free', 'Libero'), ('max_revenue', 'Massimo incasso')], default='max_revenue', max_length=20),
        ),
        migrations.RunPython(optimized_fill_everywhere, migrations.RunPython.noop),
]
