# Generated by Django 5.2.17 on 2026-09-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_outboxevent_claimed_at_outboxevent_next_attempt_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitCounter',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='core_rateli_expires_0866a5_idx')],
            },
        ),
    ]
