# Generated by Django 5.2.17 on 2026-09-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ratelimitcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='coalesce_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='salonsettings',
            name='automation_delay_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['salon', 'coalesce_key', 'status'], name='core_outbox_salon_i_9af2e7_idx'),
        ),
    ]
