# Generated by Django 5.2.17 on 2026-09-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_outboxevent_coalesce_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salon",
            name="is_demo",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
