# Generated by Django 5.2.17 on 2026-09-23 10:49
#
# Caccia ai bug del 22/09 (11-13, 11-09):
# - `db_default` sulle due colonne NOT NULL aggiunte dalla 0009: durante il
#   deploy, o dopo un deploy fallito con il container vecchio sul database già
#   migrato, il codice di prima inserisce OutboxEvent e SalonSettings senza
#   quelle colonne e ogni INSERT falliva (500 su OTP, conferme, spostamenti).
#   Su PostgreSQL sono solo `ALTER COLUMN … SET DEFAULT`, istantanee.
# - `due_at` (nullable, quindi innocua per il codice vecchio) e lo stato
#   `expired` per gli eventi scaduti prima della consegna.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_outboxevent_coalesce_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="coalesce_key",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=80
            ),
        ),
        migrations.AlterField(
            model_name="outboxevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("superseded", "Superseded"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="salonsettings",
            name="automation_delay_seconds",
            field=models.PositiveSmallIntegerField(db_default=30, default=30),
        ),
    ]
