# Generated by Django 5.2.15 on 2026-07-03 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event', models.CharField(choices=[('new_client', 'Nuovo cliente'), ('appointment_created', 'Appuntamento creato'), ('appointment_upcoming', 'Appuntamento in arrivo'), ('visit_completed', 'Visita completata'), ('birthday', 'Compleanno'), ('client_inactive', 'Cliente inattivo'), ('no_show', 'Mancata presentazione'), ('slot_freed', 'Slot liberato')], max_length=30)),
                ('offset_direction', models.CharField(choices=[('before', 'Prima'), ('after', 'Dopo')], default='after', max_length=10)),
                ('offset_value', models.PositiveIntegerField(default=0)),
                ('offset_unit', models.CharField(choices=[('minutes', 'Minuti'), ('hours', 'Ore'), ('days', 'Giorni')], default='hours', max_length=10)),
                ('send_time', models.TimeField(blank=True, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('trigger_origin', models.CharField(choices=[('yourang', 'Yourang'), ('webhook', 'Webhook')], default='yourang', max_length=10)),
                ('webhook_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message_preview', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='core.salon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
