# Generated by Django 5.2.16 on 2026-07-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_service_soak_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='yourang_item_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='service',
            name='yourang_item_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
