# Generated by Django 5.2.17 on 2026-09-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_package_yourang_item_id_service_yourang_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='description_it',
            field=models.TextField(blank=True, default=''),
        ),
    ]
