# Generated by Django 5.2.15 on 2026-07-03 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientotp',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='clients.client'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.salon'),
        ),
        migrations.AddField(
            model_name='membership',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.salon'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.salon'),
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.role'),
        ),
        migrations.AddIndex(
            model_name='clientotp',
            index=models.Index(fields=['client', 'used', 'expires_at'], name='accounts_cl_client__102eac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('salon', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'salon')},
        ),
    ]
