# Generated by Django 5.2.17 on 2026-09-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
