# Generated by Django 5.2.15 on 2026-07-03 08:19

import apps.clients.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_categories', to='core.salon')),
            ],
            options={
                'verbose_name': 'etichetta cliente',
                'verbose_name_plural': 'etichette cliente',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('wa', models.BooleanField(default=True)),
                ('lang', models.CharField(choices=[('it', 'It'), ('en', 'En')], default='it', max_length=2)),
                ('reliability', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('origin', models.CharField(blank=True, max_length=60)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('since', models.DateField(blank=True, null=True)),
                ('consents', models.JSONField(blank=True, default=apps.clients.models.default_consents)),
                ('whatsapp_reminders', models.BooleanField(default=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=120)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=120)),
                ('deposit_always', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.salon')),
                ('categories', models.ManyToManyField(blank=True, related_name='clients', to='clients.clientcategory')),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('ai', 'Ai')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('treatment', models.CharField(max_length=120)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('products', models.TextField(blank=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('outcome', models.TextField(blank=True)),
                ('duration_hold', models.CharField(blank=True, max_length=60)),
                ('advice', models.TextField(blank=True)),
                ('protocol', models.TextField(blank=True)),
                ('next_step', models.CharField(blank=True, max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='technical_sheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_sheets', to='agenda.appointment')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientcategory',
            constraint=models.UniqueConstraint(fields=('salon', 'name'), name='uniq_clientcategory_salon_name'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['salon', 'is_active'], name='clients_cli_salon_i_3e9a6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('salon', 'phone'), name='uniq_client_salon_phone'),
        ),
    ]
