# Generated by Django 5.2.16 on 2026-07-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0003_salonsettings_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='yourang_contact_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('yourang_contact_id', ''), _negated=True), fields=('salon', 'yourang_contact_id'), name='uniq_client_salon_yourang_contact'),
        ),
    ]
