# Generated by Django 5.2.17 on 2026-09-16 14:23

import apps.clients.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_appointment_yourang_event_id_and_more'),
        ('clients', '0002_client_yourang_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthday_year_known',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Donna'), ('male', 'Uomo'), ('other', 'Altro')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to='agenda.appointment'),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientnote',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ClientNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.clients.models.note_attachment_path)),
                ('name', models.CharField(max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='clients.clientnote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
