# Generated by Django 5.2.17 on 2026-09-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_gender_birthday_note_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='stripe_account_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
