# Generated by Django 5.2.17 on 2026-09-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
