# Generated by Django 5.2.17 on 2026-09-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_backfill_phone_key'),
        ('core', '0008_ratelimitcounter'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_key', ''), _negated=True), fields=('salon', 'phone_key'), name='uniq_client_salon_phone_key'),
        ),
    ]
