# Generated by Django 5.2.16 on 2026-07-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_yourangoauthstate_salon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourangconnection',
            name='credit_exhausted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yourangconnection',
            name='credit_exhausted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
