# Generated by Django 5.2.17 on 2026-09-18 09:38

from django.conf import settings
from django.db import migrations, models


def _free_duplicated_orgs(apps, schema_editor):
    """Prima del vincolo: se due saloni portano la stessa org, ne resta uno.

    Il vincolo non può essere aggiunto sopra dei duplicati, e i duplicati sono
    già oggi un guasto silenzioso (il webhook risolve il salone dall'org e ne
    trova uno a caso). Si tiene il collegamento più vecchio — quello che ha già
    ricevuto eventi — e gli altri passano in errore con la ragione scritta, così
    il titolare la vede e rifà il collegamento.
    """
    YourangConnection = apps.get_model("integrations", "YourangConnection")
    seen: set[str] = set()
    for conn in YourangConnection.objects.exclude(yourang_org_id="").order_by(
        "connected_at", "id"
    ):
        if conn.yourang_org_id in seen:
            conn.yourang_org_id = ""
            conn.status = "error"
            conn.last_error = (
                "Organizzazione Yourang già collegata a un altro salone: ricollegare."
            )
            conn.save(update_fields=["yourang_org_id", "status", "last_error"])
            continue
        seen.add(conn.yourang_org_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ratelimitcounter'),
        ('integrations', '0003_drop_local_yourang_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_free_duplicated_orgs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='yourangconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('yourang_org_id', ''), _negated=True), fields=('yourang_org_id',), name='uniq_yourang_connection_org'),
        ),
    ]
