# Ritorno al flusso OAuth diretto: il proxy connect.<brand> su cui 0003 aveva
# tagliato queste colonne non esiste ancora (nessuna rotta /auth/link, nessuna
# auth via API key, portals.yaml vuoto, connect.<brand> senza DNS). Vedi PR #22.
#
# Si va AVANTI, non si annulla 0003: in produzione 0003 e 0004 sono gia'
# applicate, e 0004 (vincolo unico sull'org) dipende da 0003. Tornare a 0002
# significherebbe perdere anche quel vincolo e lasciare un record applicato
# senza file. Le colonne tornano quindi vuote da qui, e ogni salone si
# ricollega una volta: il codice ripristinato ha di nuovo il client_secret per
# rinnovare i token, che e' cio' che al proxy mancava.

# Generated by Django 5.2.16 on 2026-09-23 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_outboxevent_coalesce_key_and_more'),
        ('integrations', '0004_yourang_org_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yourangconnection',
            name='access_token_enc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yourangconnection',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yourangconnection',
            name='refresh_token_enc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yourangconnection',
            name='scope',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='yourangconnection',
            name='webhook_secret_enc',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='YourangOAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, unique=True)),
                ('code_verifier', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.salon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
