# Generated by Django 5.2.17 on 2026-09-23 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0010_undoentry"),
        ("integrations", "0004_yourang_org_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="YourangEventSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_start", models.DateTimeField(blank=True, null=True)),
                ("remote_client", models.CharField(blank=True, max_length=255)),
                (
                    "remote_duration_min",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("remote_status", models.CharField(blank=True, max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="agenda.appointment",
                    ),
                ),
            ],
        ),
    ]
