# Generated by Django 5.2.15 on 2026-07-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipient_name', models.CharField(blank=True, max_length=120)),
                ('payment_status', models.CharField(choices=[('paid', 'Pagata'), ('unpaid', 'Da pagare')], default='unpaid', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_method', models.CharField(blank=True, max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Attiva'), ('redeemed', 'Esaurita'), ('expired', 'Scaduta')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('points', 'Punti'), ('stamps', 'Timbri'), ('tiers', 'Livelli'), ('membership', 'Membership')], default='points', max_length=12)),
                ('earn_metric', models.CharField(choices=[('per_euro', 'Per euro speso'), ('per_visit', 'Per visita'), ('per_service', 'Per servizio')], default='per_euro', max_length=12)),
                ('earn_ratio', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('reward_type', models.CharField(choices=[('coupon_amount', 'Coupon €'), ('discount_pct', 'Sconto %'), ('free_service', 'Servizio omaggio'), ('free_product', 'Prodotto omaggio'), ('gift_card', 'Gift card')], default='coupon_amount', max_length=15)),
                ('reward_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('threshold', models.PositiveIntegerField()),
                ('enrollment', models.CharField(choices=[('auto', 'Automatica'), ('request', 'Su richiesta'), ('paid', 'A pagamento')], default='auto', max_length=10)),
                ('points_expiry_months', models.PositiveSmallIntegerField(default=0)),
                ('bonus', models.JSONField(blank=True, default=dict)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='communications/')),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('audience_type', models.CharField(choices=[('labels', 'Etichette'), ('clients', 'Clienti')], default='labels', max_length=10)),
                ('audience', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Bozza'), ('scheduled', 'Programmata'), ('sent', 'Inviata')], default='draft', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.salon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('kind', models.CharField(choices=[('percent', '%'), ('amount', '€')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(choices=[('manual', 'Manuale'), ('auto', 'Automatico'), ('loyalty', 'Fedeltà')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Attivo'), ('redeemed', 'Utilizzato'), ('expired', 'Scaduto')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
