# Generated by Django 5.2.15 on 2026-07-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('marketing', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='core.salon'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='buyer_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards_bought', to='clients.client'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='recipient_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards_received', to='clients.client'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='core.salon'),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to='clients.client'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='reward_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.service'),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='core.salon'),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='marketing.loyaltyprogram'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('salon', 'code'), name='uq_coupon_salon_code'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.UniqueConstraint(fields=('salon', 'code'), name='uq_giftcard_salon_code'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyaccount',
            constraint=models.UniqueConstraint(fields=('program', 'client'), name='uq_loyalty_program_client'),
        ),
    ]
