# Generated by Django 5.2.15 on 2026-07-14 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('marketing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='gift_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.service'),
        ),
    ]
