# Generated by Django 5.2.15 on 2026-07-03 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('marketing', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('checkout', 'Checkout'), ('pos', 'Pos')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='agenda.appointment')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.location')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.salon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('other', 'Other'), ('gift_card', 'Gift Card')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gift_card', models.ForeignKey(blank=True, help_text='Gift card usata come pagamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_in_payments', to='marketing.giftcard')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('gift_card', 'Gift Card')], max_length=10)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_pct', models.PositiveSmallIntegerField(default=0)),
                ('is_gift', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='qty × unit_price × (1 − discount/100); 0 se omaggio', max_digits=10)),
                ('gift_card', models.ForeignKey(blank=True, help_text='Gift card venduta con questa riga', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_in_lines', to='marketing.giftcard')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='staff.operator')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.service')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['salon', '-created_at'], name='sales_sale_salon_i_f7e7dc_idx'),
        ),
    ]
