# Generated by Django 5.2.17 on 2026-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_deposit_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
