# Generated by Django 5.2.17 on 2026-09-23 10:26
# Movimenti di rimborso delle caparre (02-11, 05-04, 08-17): tabella nuova, nessun dato da migrare.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0010_undoentry"),
        ("core", "0009_outboxevent_coalesce_key_and_more"),
        ("sales", "0003_sale_coupon_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("other", "Other"),
                            ("gift_card", "Gift Card"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agenda.appointment",
                    ),
                ),
                (
                    "deposit_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sales.sale",
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.salon",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["salon", "created_at"],
                        name="sales_depos_salon_i_946350_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("salon", "key"), name="uniq_deposit_refund_salon_key"
                    )
                ],
            },
        ),
    ]
