# Generated by Django 5.2.17 on 2026-09-23 10:37
#
# Buono sconto ripartito sulle righe (05-18). Per le vendite già registrate con
# un buono lo sconto stava solo sul totale: la migrazione dati lo ripartisce
# come fa ora `sales.services._spread_coupon` (algoritmo copiato qui, per non
# dipendere dal codice vivo), così anche il fatturato per operatrice dei mesi
# passati torna con l'incasso. Tocca solo le vendite con coupon_discount > 0 le
# cui righe sommano ancora totale + sconto; rieseguirla non cambia niente.

from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models

CENT = Decimal("0.01")


def spread_recorded_coupons(apps, schema_editor):
    Sale = apps.get_model("sales", "Sale")
    SaleLine = apps.get_model("sales", "SaleLine")
    for sale in Sale.objects.filter(coupon_discount__gt=0).order_by("id").iterator():
        lines = list(SaleLine.objects.filter(sale_id=sale.id).order_by("id"))
        if any(line.coupon_share for line in lines):
            continue
        if sum((line.amount for line in lines), Decimal("0.00")) != sale.total + sale.coupon_discount:
            continue  # già ripartita, o corretta a mano: non si tocca
        eligible = [line for line in lines if line.line_type != "gift_card" and line.amount > 0]
        base = sum((line.amount for line in eligible), Decimal("0.00"))
        if base <= 0:
            continue
        discount = sale.coupon_discount
        ordered = sorted(eligible, key=lambda line: (line.amount, line.id))
        shares = {line.id: Decimal("0.00") for line in eligible}
        remaining = discount
        for line in ordered[:-1]:
            share = min((discount * line.amount / base).quantize(CENT, rounding=ROUND_HALF_UP), line.amount)
            shares[line.id] = share
            remaining -= share
        for line in reversed(ordered):
            if remaining <= 0:
                break
            extra = min(remaining, line.amount - shares[line.id])
            shares[line.id] += extra
            remaining -= extra
        for line in eligible:
            if shares[line.id]:
                line.coupon_share = shares[line.id]
                line.amount = line.amount - shares[line.id]
                line.save(update_fields=["amount", "coupon_share"])


def restore_line_amounts(apps, schema_editor):
    SaleLine = apps.get_model("sales", "SaleLine")
    for line in SaleLine.objects.filter(coupon_share__gt=0).iterator():
        line.amount = line.amount + line.coupon_share
        line.coupon_share = Decimal("0.00")
        line.save(update_fields=["amount", "coupon_share"])


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_caccia22_caparra_rimborsi"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleline",
            name="coupon_share",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="saleline",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="qty × unit_price × (1 − discount/100) − coupon_share; 0 se omaggio",
                max_digits=10,
            ),
        ),
        migrations.RunPython(spread_recorded_coupons, restore_line_amounts),
    ]
